// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmvV5JN8lgPK5YA11BioSM2yVUQzDPOM',
    appId: '1:189083447218:web:fbda23fccdcf313c443eab',
    messagingSenderId: '189083447218',
    projectId: 'flutter-intern-assignment',
    authDomain: 'flutter-intern-assignment.firebaseapp.com',
    storageBucket: 'flutter-intern-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanygvPnYnxGz21il2b4STnF0kUiTX8Tw',
    appId: '1:189083447218:android:562ef395336f2af8443eab',
    messagingSenderId: '189083447218',
    projectId: 'flutter-intern-assignment',
    storageBucket: 'flutter-intern-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy797jO1OmPt9BbBCeP34ixVjpXnjE-RM',
    appId: '1:189083447218:ios:54e2949e6669a03e443eab',
    messagingSenderId: '189083447218',
    projectId: 'flutter-intern-assignment',
    storageBucket: 'flutter-intern-assignment.firebasestorage.app',
    iosBundleId: 'com.example.flutterInternAssignment',
  );
}
